services:
  postgresql:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
    ports:
      - "5433:5432"
  redis:
    image: redis
    container_name: redis_container
    ports:
      - "6379:6379"